### PR TITLE
Handle almost-transparent and transparent pixels better

### PR DESCRIPTION
**Pull request by trotzig**
I came across a case where one pixel is almost transparent and the other is fully transparent. Consider these pixels:

[ 1, 46, 250, 0 ]
[ 1, 42, 250, 4 ]

With our old logic, there was a color-delta of `1` between these pixels. If we blend them both with white, we instead get a very low color-delta value.

At first I was going to always blend with white, but I realized we are using fully transparent as a signal that there is a gap/missing pixels in either the before or after image. So I instead changed it to "intentional transparency" where something like

[255, 255, 255, 0]
[0, 0, 0, 0]
[100, 100, 100, 0]

would be considered "intentional transparency". Of course, this assumption can't always be made. But for us I think we can use it to get rid of the edge-case that I present here. There's still a risk that we'll encounter "wild" transparency with r===g===b but at least this is better than what we have.

### CODE REVIEW

**Review by lencioni — COMMENTED** [review]
I don't think I understand, why can't we always blend with white?

**Comment by trotzig** [comment]
I thought we used fully transparent when constructing the "gaps" in the image. But I was wrong, it looks like we use a semi-transparent pixel. 

https://github.com/happo/lcs-image-diff/blob/809bb90e60615cafd4ac6911abc8deec3640cde1/src/computeAndInjectDiffs.js#L51

I'll change to blending with white and see what happens.

**Comment by trotzig** [comment]
Okay, seems like commit d4ecfac8604a25df is relevant here. Basically the avoidance of blending with white for fully transparent pixels was to make diffs that are different in width better. The missing area to the right for one of the images will be represented as fully transparent. If we blend it with white and then run color-delta there would be no difference.

**Comment by trotzig** [comment]
Pushed another commit to clarify some intentions. While this isn't great, it's slightly better than what we currently have.

**Pull request merged**
